const axios = require('axios');

/**
 * Whitepaper Agent - Specializes in creating and analyzing whitepapers
 */
exports.process = async (prompt, context, options = {}) => {
  try {
    // Construct the system prompt for the Whitepaper agent
    const systemPrompt = `You are a Whitepaper Agent specializing in creating comprehensive, professional whitepapers for blockchain and AI projects. 
    
Your expertise includes:
- Technical writing and documentation
- Blockchain technology concepts
- Project vision and roadmap development
- Market analysis and positioning
- Clear explanation of complex technical concepts

Format your responses in Markdown with proper headings, bullet points, and sections.`;

    // Construct the user message with context
    const userMessage = constructUserMessage(prompt, context);
    
    // Call Claude API via OpenHands
    const response = await callClaudeAPI(systemPrompt, userMessage, options);
    
    return {
      content: response.content,
      format: 'markdown',
      metadata: {
        agentType: 'whitepaper',
        timestamp: new Date().toISOString(),
        promptTokens: response.usage?.prompt_tokens || 0,
        completionTokens: response.usage?.completion_tokens || 0
      }
    };
  } catch (error) {
    console.error('Error in Whitepaper Agent:', error);
    throw new Error(`Whitepaper Agent error: ${error.message}`);
  }
};

/**
 * Construct a user message with context
 */
function constructUserMessage(prompt, context) {
  // Extract relevant history from context
  const relevantHistory = context.relevantHistory || [];
  
  // Format the history as a string
  let historyText = '';
  if (relevantHistory.length > 0) {
    historyText = 'Previous interactions:\n\n' + 
      relevantHistory.map(item => 
        `Agent: ${item.agentType}\nPrompt: ${item.prompt}\nResponse: ${summarizeResponse(item.response)}\n`
      ).join('\n---\n\n');
  }
  
  // Combine history with the current prompt
  return `${historyText ? historyText + '\n\nCurrent request:\n' : ''}${prompt}`;
}

/**
 * Summarize a response for inclusion in context
 */
function summarizeResponse(response) {
  if (!response || !response.content) return 'No response';
  
  // For brevity in the context, limit the response summary
  const maxLength = 200;
  let content = response.content;
  
  if (content.length > maxLength) {
    content = content.substring(0, maxLength) + '...';
  }
  
  return content;
}

/**
 * Call the Claude API via OpenHands
 */
async function callClaudeAPI(systemPrompt, userMessage, options = {}) {
  try {
    // This is a placeholder for the actual Claude API integration
    // In a real implementation, this would make an API call to Claude via OpenHands
    
    // Simulate API response for now
    return {
      content: `# Sample Whitepaper Response

## Introduction
This is a sample response from the Whitepaper Agent. In a real implementation, this would be generated by Claude 4 Sonnet.

## Key Features
- Professional whitepaper formatting
- Technical accuracy
- Clear explanations of complex concepts

## Next Steps
Implement the actual Claude API integration to generate real responses.`,
      usage: {
        prompt_tokens: 500,
        completion_tokens: 300
      }
    };
  } catch (error) {
    console.error('Error calling Claude API:', error);
    throw new Error(`Claude API error: ${error.message}`);
  }
}